#!perl

# AUTHORITY
# DATE
# DIST
# VERSION

use 5.010001;
use strict;
use warnings;

use Perinci::CmdLine::Any;

our %SPEC;

$SPEC{extract_youtube_video_ids} = {
    v => 1.1,
    summary => 'Extract YouTube video IDs from filename/URL '.
        '(in arguments/stdin)',
    args => {
        args => {
            schema => ['array*', of=>'str*'],
            req => 1,
            pos => 0,
            greedy => 1,
            cmdline_src => 'stdin_or_args',
        },
    },
    result_naked => 1,
    examples => [
        {
            argv => [
                'https://www.youtube.com/watch?v=rp4UwPZfRis',
                '$100,000 Name That Tune - Nick vs. Carol-SY-DnVZeFH0.mp4',
                'GNdALsnBjh8',
            ],
            result => [200, "OK", [
                'rp4UwPZfRis',
                'SY-DnVZeFH0',
                'GNdALsnBjh8',
            ]],
        },
    ],
};
sub extract_youtube_video_ids {
    require YouTube::Util;

    my %args = @_;

    my @res;
    for my $arg (@{ $args{args} }) {
        my $res = YouTube::Util::extract_youtube_video_id($arg);
        push @res, $res if $res;
    }
    \@res;
}

Perinci::CmdLine::Any->new(
    url => "/main/extract_youtube_video_ids",
)->run;

# ABSTRACT:
# PODNAME:
